# Generated by Django 4.1.4 on 2022-12-31 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_feedbaks_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='phone',
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
